### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by 11sma** [mrcagney/gtfstk#29]
I'm trying to install with 

```
[root@server tmp]# pip --version
pip 20.0.2 from /usr/lib/python3.6/site-packages/pip (python 3.6)
```

using 
`[root@server tmp]# pip install gtfs_kit`

but cannot be done

```
[root@server tmp]# pip install gtfs_kit
Collecting gtfs_kit
  Using cached gtfs_kit-3.0.1-py3-none-any.whl (61 kB)
Collecting geopandas<1
  Using cached geopandas-0.7.0-py2.py3-none-any.whl (928 kB)
Collecting rtree<1
  Using cached Rtree-0.9.4.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qp19li1h/rtree/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qp19li1h/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qp19li1h/rtree/pip-egg-info
         cwd: /tmp/pip-install-qp19li1h/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qp19li1h/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-qp19li1h/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-qp19li1h/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-qp19li1h/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib64/python3.6/ctypes/__init__.py", line 356, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib64/python3.6/ctypes/__init__.py", line 361, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python3.6: undefined symbol: Error_GetLastErrorNum
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any suggestion what i'm doing wrong?

Thanks

**Comment by araichev** [comment]
See [this GTFS Kit issue](https://github.com/mrcagney/gtfs_kit/issues/2#event-3090461115)
